# 服务端口
server.port=8082

# 企业微信配置
wechat.work.corpid=wwce6b569b8529bd53
wechat.work.corpsecret=XOYMZI7T3VHq5G6wgce4MXMPnUnkTIhGfvETnRLERvM

# 文件上传大小限制
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
